# Enhanced MAPPO算法配置文件
# the path of algorithm class
algorithm_path: agents.emappo.EnhancedMAPPOAgent
trainer_path: trainers.emappo_trainer.EnhancedMAPPOTrainer

# Network Design
hidden_dim: 128
num_attention_heads: 4  # 注意力头数
use_attention: true  # 是否使用注意力机制

# DL & RL hyper-params
learning_rate: 0.0001
use_separate_lr: false
actor_lr: 0.0001
critic_lr: 0.0001
batch_size: 32
gamma: 0.99
gae_lambda: 0.95
normalize_advantages: true
advantage_normalize_mode: global
value_loss_coef: 1
grad_norm_clip: 10.0

# PPO hyper-params
clip_param: 0.2
entropy_coef: 0.01
ppo_epochs: 4

# Value function improvements
use_huber_loss: True
value_clip_param: 0.2

# Learning rate scheduler
use_lr_scheduler: True
lr_scheduler_T_max: 1000
lr_scheduler_eta_min: 1e-6

# Training hyper-params
training_action_mode: sample
testing_action_mode: greedy
num_max_keep_ckpt: 5  # 最多保存的检查点数量